name: PR Validation

on:
  pull_request:
    branches: [main]
    paths:
      - 'force-app/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global

      - name: Show CLI version
        run: sf version

      - name: Install scanner
        run: sf plugins install @salesforce/sfdx-scanner

      - name: Run static code analysis
        run: sf scanner run --target force-app

      - name: Authenticate DevHub
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
          chmod 600 server.key
          sf org login jwt \
            --username ${{ secrets.SF_USERNAME }} \
            --jwt-key-file server.key \
            --client-id ${{ secrets.SF_KEY }} \
            --instance-url https://resilient-bear-fqihg6-dev-ed.trailblaze.my.salesforce-setup.com \
            --set-default-dev-hub \
            --alias devhub

      - name: Verify Dev Hub login
        run: sf org list

      - name: Verify Dev Hub login
        run: sf org display --target-org devhub

      - name: Check scratch org JSON
        run: |
          echo "File contents:"
          cat config/project-scratch-def.json
          echo "File type:"
          file config/project-scratch-def.json
          
      - name: Create Scratch Org
        run: |
          sf org create scratch \
            --definition-file config/project-scratch-def.json \
            --duration-days 1 \
            --target-dev-hub devhub \
            --set-default \
            --alias ci_org

      - name: Push source to scratch org
        run: sf project deploy start --source-dir force-app --wait 10

      - name: Run Apex tests
        run: sf apex run test --test-level RunLocalTests --wait 20